name: build dist

on:
  push:
  pull_request:

jobs:
  build-android:
    name: build Android
    runs-on: ubuntu-22.04
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: build
      run: ./gradlew :android:assembleDebug
    - name: upload build failure logs
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: build-failure-logs-android
        path: |
          kmmk/build/reports/
          android/build/reports/

  build-desktop:
    name: 'build Desktop on ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-12, windows-2019]
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: apt update and install
      if: matrix.os == 'ubuntu-22.04'
      run: |
        sudo apt-get update
    - name: build
      run: ./gradlew :desktop:build
    - name: upload build failure logs
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: test-failure-logs-${{ matrix.os }}
        path: |
          kmmk/build/reports/
          desktop/build/reports/

