name: build dist

on:
  push:
  pull_request:

jobs:
  build-android:
    name: build Android
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v2.3.4
      with:
        submodules: recursive
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: build
      run: ./gradlew :android:assembleDebug
    - name: upload build failure logs
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: build-failure-logs-android
        path: |
          kmmk/build/reports/
          android/build/reports/
    - name: upload artifact - Android
      uses: actions/upload-artifact@v2
      with:
        name: kmmk-android
        path:
          android/build/outputs/apk/debug/*.apk

  build-desktop:
    name: 'build Desktop on ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-10.15, windows-latest]
    steps:
    - name: checkout
      uses: actions/checkout@v2.3.4
      with:
        submodules: recursive
    - name: set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 16
    - name: apt update and install
      if: matrix.os == 'ubuntu-20.04'
      run: |
        sudo apt-get update
    - name: build
      run: ./gradlew package
    - name: upload build failure logs
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: test-failure-logs-${{ matrix.os }}
        path: |
          kmmk/build/reports/
          desktop/build/reports/
    - name: upload artifact - Desktop
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: kmmk-${{ matrix.os }}
        path: |
          desktop/build/compose/binaries/main/deb/*.deb
          desktop/build/compose/binaries/main/dmg/*.dmg
          desktop/build/compose/binaries/main/msi/*.msi

