name: build dist

on:
  push:
  pull_request:

jobs:
  build:
    name: 'build Desktop on ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-13, macos-14, windows-latest]
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: apt update and install
      if: matrix.os == 'ubuntu-22.04'
      run: |
        sudo apt-get update

    - name: build
      run: ./gradlew build package

    - name: upload build failure logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-failure-logs-${{ matrix.os }}
        path: |
          composeApp/build/reports/

    - name: upload artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: kmmk-${{ matrix.os }}
        path: |
          composeApp/build/outputs/apk/debug/*.apk
          composeApp/build/outputs/bundle/release/*.aab
          composeApp/build/dist/wasmJs/
          composeApp/build/compose/binaries/main/deb/*.deb
          composeApp/build/compose/binaries/main/dmg/*.dmg
          composeApp/build/compose/binaries/main/msi/*.msi
